name: CI + CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  validate-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check HTML syntax
        run: |
          sudo apt-get update
          sudo apt-get install -y tidy
          tidy -errors -q index.html || true

      - name: Check CSS syntax
        run: |
          npm install -g stylelint
          stylelint "**/*.css" || true

  deploy:
    runs-on: ubuntu-latest
    needs: validate-code

    steps:

      - uses: actions/checkout@v3

      - name: Prepare SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Server Host Key
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          scp index.html style.css \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/

