name: CI + CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  validate-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Vérifier syntaxe HTML
        run: |
          sudo apt install -y tidy
          tidy -errors -q index.html || true

      - name: Vérifier syntaxe CSS
        run: |
          npm install -g stylelint
          stylelint "**/*.css" || true

  deploy:
    runs-on: ubuntu-latest
    needs: validate-code

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy website to VM_Client1
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "sudo mkdir -p /var/www/html"

          scp -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no index.html style.css \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/

