name: Mini CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  validate-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Vérifier syntaxe HTML
        run: |
          sudo apt install -y tidy
          tidy -errors -q index.html || true

      - name: Vérifier syntaxe CSS
        run: |
          npm install -g stylelint
          stylelint "**/*.css" || true

      - name: Valider le code
        run: echo "Code validé ✔️"

