name: CI + CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  validate-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check HTML syntax
        run: |
          sudo apt-get update
          sudo apt-get install -y tidy
          tidy -errors -q index.html || true

      - name: Check CSS syntax
        run: |
          npm install -g stylelint
          stylelint "**/*.css" || true

  deploy:
    runs-on: self-hosted     # <---- TRÃˆS IMPORTANT
    needs: validate-code

    steps:
      - uses: actions/checkout@v3

      - name: Deploy files locally
        run: |
          sudo cp index.html style.css /var/www/html/
