name: CI + CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  validate-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check HTML syntax
        run: |
          sudo apt install -y tidy
          tidy -errors -q index.html || true

      - name: Check CSS syntax
        run: |
          npm install -g stylelint
          stylelint "**/*.css" || true

  deploy:
    runs-on: ubuntu-latest
    needs: validate-code

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare SSH
        run: |
          mkdir -p $RUNNER_TEMP/ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $RUNNER_TEMP/ssh/id_ed25519
          chmod 600 $RUNNER_TEMP/ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> $RUNNER_TEMP/ssh/known_hosts || true

      - name: Deploy files to VM
        run: |
          scp -i $RUNNER_TEMP/ssh/id_ed25519 index.html style.css \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/
